name: "MeshMonitor"
description: "Web-based monitoring for Meshtastic mesh networks"
version: "0.0.3"
slug: "meshmonitor"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
boot: auto
homeassistant_api: true

ports:
  3001/tcp: 3001

webui: "http://[HOST]:[PORT:3001]/"

options:
  meshtastic_node_ip: "192.168.1.100"
  allowed_origins: ""

schema:
  meshtastic_node_ip: str
  allowed_origins: str?
